import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Logo from "@/public/biglogo.svg";
import { Button } from "@/components/ui/button";
import { GitHubLogoIcon, TwitterLogoIcon } from "@radix-ui/react-icons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col`}
      >
        <header className="sm:mx-10 mx-4 mt-5">
          <div className="flex items-center justify-between">
            <Link href="/">
              <Image src={Logo} alt="Logo" width={400} height={50} />
            </Link>
            <Button
              asChild
              variant="outline"
              className="hidden sm:inline-flex gap-2"
            >
              <Link href="https://github.com/nutlope/napkins" target="_blank">
                <GitHubLogoIcon className="size-4" />
                GitHub
              </Link>
            </Button>
          </div>
        </header>

        <main className="grow flex flex-col">{children}</main>

        <footer className="flex items-center justify-between sm:mx-10 mx-4 mb-3 text-gray-600 text-sm">
          <p>
            Powered by{" "}
            <a
              href="https://dub.sh/together-ai"
              target="_blank"
              className="font-bold hover:underline underline-offset-4"
            >
              Together AI
            </a>{" "}
            and{" "}
            <a
              // TODO: Update this with blog post link
              href="https://dub.sh/together-ai"
              target="_blank"
              className="font-bold hover:underline underline-offset-4"
            >
              Llama 3.2 Vision
            </a>
          </p>
          <div className="flex gap-4">
            <Button
              asChild
              variant="ghost"
              className="hidden sm:inline-flex gap-2"
            >
              <Link href="https://github.com/nutlope/napkins" target="_blank">
                <GitHubLogoIcon className="size-4" />
                GitHub
              </Link>
            </Button>
            <Button
              asChild
              variant="ghost"
              className="hidden sm:inline-flex gap-2"
            >
              <Link href="https://twitter.com/nutlope" target="_blank">
                <TwitterLogoIcon className="size-4" />
                Twitter
              </Link>
            </Button>
          </div>
        </footer>
      </body>
    </html>
  );
}
